### ISSUE TITLE
Customize run name based on training configs

### ISSUE THREAD

**Issue by vipulSharma18** [rbalestr-lab/stable-SSL#26]
wandb and local run name to be generated automatically as per the training configs

**Comment by RandallBalestriero** [comment]
wandb will automatically generate a name if none is given by the user. I would advocate against overriding the wandb logic to handle automatic name generation since the naming convention would be very user specific. Thoughts @huguesva ?

**Comment by vipulSharma18** [comment]
We're already overriding the naming convention with this:
`datetime.now().strftime("%Y%m%d_%H%M%S.%f")`

So I thought I'll make it more meaningful by making it this:
`'SimCLR_resnet9_eps_1000_optim_LARS' + '_' + datetime.now().strftime("%Y%m%d_%H%M%S.%f")`

**Comment by vipulSharma18** [comment]
Code which overrides run name: https://github.com/rbalestr-lab/stable-SSL/blob/main/stable_ssl/config.py#L178

**Comment by RandallBalestriero** [comment]
This is only for local folder, not for wandb. And the date time override is also aligned with Hydra logic and other frameworks (that the minimum info to add to make sure deduplication). However I would advise against using further customization with config args for the naming. If users want more personalization on that they can easily override that logic from the Trainer? @huguesva maybe we can add a method like `name_folder` that users can use to customize the naming from args?

**Comment by huguesva** [comment]
I agree with @RandallBalestriero that we should not override the wandb logic.

**Comment by huguesva** [comment]
yes ok for the ``name_folder``method.

**Comment by vipulSharma18** [comment]
Change not required, closing issue.
