### ISSUE TITLE
Hugging Face Integration for Models and Datasets

### ISSUE THREAD

**Issue by vipulSharma18** [rbalestr-lab/stable-SSL#59]
Huggingface caches dataset & models but in user directory by default. We'll need to add a config to specify huggingface cache directory. 

We want huggingface integration for both models and data.

```Files from Hugging Face are stored as usual in the huggingface_hub cache, which is at ~/.cache/huggingface/hub by default```

[Slack Message](https://rbalestr-lab.slack.com/archives/C07RZ992MAT/p1730659353918089)

**Comment by RandallBalestriero** [comment]
This is now down for datasets (you can specify any arg when calling the `load_dataset` method from the config (you can see the imagenette example for details).
Remains to integrate the hugging face models
