### ISSUE TITLE
[Feature Request] Support for generic datasets which are an instance of ImageFolder

### ISSUE THREAD

**Issue by vipulSharma18** [rbalestr-lab/stable-SSL#84]
1. Support generic kwargs if user is using an instance of ImageFolder.
2. Support custom datasets which are derived from ImageFolder and have their own `__init__` and `get_item`. Something like VISSL data catalogue where users can define new datasets to use and VISSL looks in data catalogue to find those datasets.

**Comment by RandallBalestriero** [comment]
Done in https://github.com/rbalestr-lab/stable-SSL/pull/97 where any type of dataset can be specified in the config
